### ISSUE TITLE
System.Net.Http.HttpRequestException : Response status code does not indicate success: 401 (Unauthorized).    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()

### ISSUE THREAD

**Issue by jaiswati** [microsoftgraph/webjobs-webhooks-sample#2]
Hi,

I have received this  error message while I run the sample..
I have ensured that Application has correct permissions -- Read Active Directory data
and all the AppSettings values are correctFound the following functions:
WebHooksSample.Functions.ManageSubscriptions
WebHooksSample.Functions.OnNotificationReceived
ServicePointManager.DefaultConnectionLimit is set to the default value of 2. This can limit the connection throughput to services like Azure Storage. For more information, see https://aka.ms/webjobs-connections.
Singleton lock acquired (b1f163b119a34a45863ef2d93884dbb6/WebHooksSample.Functions.ManageSubscriptions.Listener)
Function 'WebHooksSample.Functions.ManageSubscriptions' is configured to run on startup. Executing now.
Executing 'Functions.ManageSubscriptions' (Reason='Timer fired at 2018-04-29T11:53:15.6299556+00:00', Id=38200e7c-2bfa-47eb-b482-737e1b3d1855)
Exception while executing function: Functions.ManageSubscriptions
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.ManageSubscriptions ---> System.Net.Http.HttpRequestException : Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at async WebHooksSample.Functions.ManageSubscriptions(TimerInfo timer,IBinder binder,CancellationToken cancellationToken,TextWriter log) at C:\Users\jaiswati\Downloads\webjobs-webhooks-sample-master\webjobs-webhooks-sample-master\WebHooksSample\Functions.cs : 128
   at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   End of inner exception
Exception while executing function: Functions.ManageSubscriptions
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.ManageSubscriptions ---> System.Net.Http.HttpRequestException : Response status code does not indicate success: 401 (Unauthorized).

**Comment by baywet** [comment]
Hi @jaiswati 
Thanks for your question and sorry about the late reply.
We're archiving this sample as it is old and lacks maintenance.
If you have any questions about using the Microsoft Graph from Azure Functions or Azure Webjobs, please post those on [stackoverflow](https://stackoverflow.com/questions/tagged/microsoft-graph) with the microsoft-graph tag. We do have a dedicated triage system that's more reactive than issues follow up in samples repositories.
